export { default as Footer } from '../../components/footer.vue'
export { default as GnbHeader } from '../../components/gnbHeader.vue'
export { default as Header } from '../../components/header.vue'
export { default as ApiAxios } from '../../components/api/axios.js'
export { default as DummyAward } from '../../components/dummy/award.js'
export { default as DummyAwardEn } from '../../components/dummy/awardEn.js'
export { default as MainBannerModule } from '../../components/main/bannerModule.vue'
export { default as MainCompany } from '../../components/main/company.vue'
export { default as MainCompanyAwards } from '../../components/main/companyAwards.vue'
export { default as MainCtaModule } from '../../components/main/ctaModule.vue'
export { default as MainBanner } from '../../components/main/mainBanner.vue'
export { default as MainSlider } from '../../components/main/mainSlider.vue'
export { default as MainProducts } from '../../components/main/products.vue'
export { default as MainSlideCarousel } from '../../components/main/slideCarousel.vue'
export { default as MainSuppoert } from '../../components/main/suppoert.vue'
export { default as MainUseCase } from '../../components/main/useCase.vue'
export { default as MixinsMixin } from '../../components/mixins/mixin.js'
export { default as NewsCommonBaner } from '../../components/news/CommonBaner.vue'
export { default as Paging } from '../../components/paging/paging.vue'
export { default as ModulesBanner } from '../../components/modules/Banner.vue'
export { default as ModulesBoard } from '../../components/modules/Board.vue'
export { default as ModulesBoardView } from '../../components/modules/BoardView.vue'
export { default as ModulesCalculatorPopup } from '../../components/modules/CalculatorPopup.vue'
export { default as ModulesDialogMobile } from '../../components/modules/Dialog-Mobile.vue'
export { default as ModulesDropdown } from '../../components/modules/Dropdown.vue'
export { default as ModulesGallery } from '../../components/modules/Gallery.vue'
export { default as ModulesHeading } from '../../components/modules/Heading.vue'
export { default as ModulesLibrary } from '../../components/modules/Library.vue'
export { default as ModulesLibraryView } from '../../components/modules/LibraryView.vue'
export { default as ModulesNewsletter } from '../../components/modules/Newsletter.vue'
export { default as ModulesPopup } from '../../components/modules/Popup.vue'
export { default as ModulesPopupConfirm } from '../../components/modules/PopupConfirm.vue'
export { default as ModulesPopupVideo } from '../../components/modules/PopupVideo.vue'
export { default as ModulesRequiredPopup } from '../../components/modules/RequiredPopup.vue'
export { default as ModulesSnb } from '../../components/modules/Snb.vue'
export { default as ModulesSubSolutionMenu } from '../../components/modules/SubSolutionMenu.vue'
export { default as ModulesSupportModule } from '../../components/modules/SupportModule.vue'
export { default as ModulesYoutubeFullscreen } from '../../components/modules/YoutubeFullscreen.vue'
export { default as ProductsNewBgPartData } from '../../components/products/NewBgPartData.js'
export { default as ProductsNewEffectPartData } from '../../components/products/newEffectPartData.js'
export { default as ProductsNewEffectPartDataEn } from '../../components/products/newEffectPartData_en.js'
export { default as ProductsNewModuleData } from '../../components/products/newModuleData.js'
export { default as ProductsNewModuleDataEn } from '../../components/products/newModuleData_en.js'
export { default as PolicySubMenuPayment } from '../../components/policy/subMenuPayment.vue'
export { default as PolicySubMenuPolicy } from '../../components/policy/subMenuPolicy.vue'
export { default as PolicySubMenuTerms } from '../../components/policy/subMenuTerms.vue'
export { default as SubscriptionComForm } from '../../components/subscription/comForm.vue'
export { default as SubscriptionComModal } from '../../components/subscription/comModal.vue'
export { default as SubscriptionForm } from '../../components/subscription/form.vue'
export { default as SubscriptionModal } from '../../components/subscription/modal.vue'
export { default as SubscriptionProForm } from '../../components/subscription/proForm.vue'
export { default as SubscriptionProModal } from '../../components/subscription/proModal.vue'
export { default as SupportSubMenu } from '../../components/support/SubMenu.vue'
export { default as SupportFaq } from '../../components/support/faq.vue'
export { default as SupportFaqBanner } from '../../components/support/faqBanner.vue'
export { default as SupportHeadBanner } from '../../components/support/headBanner.vue'
export { default as SupportHeadBannerCENTER } from '../../components/support/headBannerCENTER.vue'
export { default as SupportHeadBannerProduct } from '../../components/support/headBannerProduct.vue'
export { default as SupportInquiry } from '../../components/support/inquiry.vue'
export { default as SupportInquiryBanner } from '../../components/support/inquiryBanner.vue'
export { default as SupportLearnBanner } from '../../components/support/learnBanner.vue'
export { default as SupportLearningCenter } from '../../components/support/learning-center.vue'
export { default as SupportNotice } from '../../components/support/notice.vue'
export { default as CompanyPagesRecruit } from '../../components/company/pages/Recruit.vue'
export { default as CompanyPagesBrand } from '../../components/company/pages/brand.vue'
export { default as CompanyValue } from '../../components/company/pages/companyValue.vue'
export { default as CompanyPagesIntroduce } from '../../components/company/pages/introduce.vue'
export { default as CompanyPartialsContactModule } from '../../components/company/partials/contactModule.vue'
export { default as CompanyPartialsSubMenu } from '../../components/company/partials/subMenu.vue'
export { default as CompanyPartialsSubMenuBrand } from '../../components/company/partials/subMenuBrand.vue'
export { default as CompanyPartialsSubMenuIr } from '../../components/company/partials/subMenuIr.vue'
export { default as GnbCompany } from '../../components/Gnb/Company/index.vue'
export { default as GnbContact } from '../../components/Gnb/Contact/index.vue'
export { default as GnbFreeTrials } from '../../components/Gnb/FreeTrials/index.vue'
export { default as GnbPricing } from '../../components/Gnb/Pricing/index.vue'
export { default as GnbProducts } from '../../components/Gnb/Products/index.vue'
export { default as GnbSolution } from '../../components/Gnb/Solution/index.vue'
export { default as GnbHeaderPartialMobileHeader } from '../../components/Gnb/headerPartial/mobileHeader.vue'
export { default as ProductsPagesMS } from '../../components/products/pages/MS.vue'
export { default as ProductsPagesMake } from '../../components/products/pages/Make.vue'
export { default as ProductsPagesPmain } from '../../components/products/pages/Pmain.vue'
export { default as ProductsPagesRemote } from '../../components/products/pages/Remote.vue'
export { default as ProductsPagesTrack } from '../../components/products/pages/Track.vue'
export { default as ProductsPagesTwin } from '../../components/products/pages/Twin.vue'
export { default as ProductsPagesView } from '../../components/products/pages/View.vue'
export { default as ProductsPartialsBenefitPart } from '../../components/products/partials/BenefitPart.vue'
export { default as ProductsPartialsBgSlidePart } from '../../components/products/partials/BgSlidePart.vue'
export { default as ProductsPartialsEffectPart } from '../../components/products/partials/EffectPart.vue'
export { default as ProductsPartialsExamplePart } from '../../components/products/partials/ExamplePart.vue'
export { default as ProductsPartialsFunctionPart } from '../../components/products/partials/FunctionPart.vue'
export { default as ProductsPartialsFunctionPart2 } from '../../components/products/partials/FunctionPart2.vue'
export { default as ProductsPartialsIntroducePart } from '../../components/products/partials/IntroducePart.vue'
export { default as ProductsPartialsNewBgSlide } from '../../components/products/partials/NewBgSlide.vue'
export { default as ProductsPartialsNewBgSlideEnter } from '../../components/products/partials/NewBgSlideEnter.vue'
export { default as ProductsPartialsNewBgSlideEpc } from '../../components/products/partials/NewBgSlideEpc.vue'
export { default as ProductsPartialsNewBgSlideMake } from '../../components/products/partials/NewBgSlideMake.vue'
export { default as ProductsPartialsNewBgSlideMotor } from '../../components/products/partials/NewBgSlideMotor.vue'
export { default as ProductsPartialsNewBgSlideOil } from '../../components/products/partials/NewBgSlideOil.vue'
export { default as ProductsPartialsNewBgSlideRemote } from '../../components/products/partials/NewBgSlideRemote.vue'
export { default as ProductsPartialsNewBgSlideTrack } from '../../components/products/partials/NewBgSlideTrack.vue'
export { default as ProductsPartialsNewBgSlideTwin } from '../../components/products/partials/NewBgSlideTwin.vue'
export { default as ProductsPartialsNewBgSlideView } from '../../components/products/partials/NewBgSlideView.vue'
export { default as ProductsPartialsNewBgSlideinfra } from '../../components/products/partials/NewBgSlideinfra.vue'
export { default as ProductsPartialsNewEffectPart } from '../../components/products/partials/NewEffectPart.vue'
export { default as ProductsPartialsNewEffectPartMake } from '../../components/products/partials/NewEffectPartMake.vue'
export { default as ProductsPartialsNewEffectRemote } from '../../components/products/partials/NewEffectRemote.vue'
export { default as ProductsPartialsNewEffectTrack } from '../../components/products/partials/NewEffectTrack.vue'
export { default as ProductsPartialsNewEffectTwin } from '../../components/products/partials/NewEffectTwin.vue'
export { default as ProductsPartialsNewEffectView } from '../../components/products/partials/NewEffectView.vue'
export { default as ProductsMainBanner } from '../../components/products/partials/ProductsMainBanner.vue'
export { default as ProductsPartialsSupportPart } from '../../components/products/partials/SupportPart.vue'
export { default as ProductsPartialsXRSolution } from '../../components/products/partials/XRSolution.vue'
export { default as ProductsPartialsBottomBannerRemote } from '../../components/products/partials/bottomBannerRemote.vue'
export { default as ProductsPartialsDataModule } from '../../components/products/partials/dataModule.vue'
export { default as ProductsPartialsNavi } from '../../components/products/partials/navi.vue'
export { default as ProductsPartialsNewModule } from '../../components/products/partials/newModule.vue'
export { default as ProductsPartialsProductProperty } from '../../components/products/partials/productProperty.vue'
export { default as ProductsPartialsSubBanner } from '../../components/products/partials/subBanner.vue'
export { default as ProductsPartialsSubBannerMake } from '../../components/products/partials/subBannerMake.vue'
export { default as ProductsPartialsSubBannerTrack } from '../../components/products/partials/subBannerTrack.vue'
export { default as ProductsPartialsSubBannerTwin } from '../../components/products/partials/subBannerTwin.vue'
export { default as ProductsPartialsSubBannerView } from '../../components/products/partials/subBannerView.vue'
export { default as ProductsPartialsSubMenuMake } from '../../components/products/partials/subMenuMake.vue'
export { default as ProductsPartialsSubMenuMs } from '../../components/products/partials/subMenuMs.vue'
export { default as ProductsPartialsSubMenuProduct } from '../../components/products/partials/subMenuProduct.vue'
export { default as ProductsPartialsSubMenuTrack } from '../../components/products/partials/subMenuTrack.vue'
export { default as ProductsPartialsSubMenuTwin } from '../../components/products/partials/subMenuTwin.vue'
export { default as ProductsPartialsSubMenuView } from '../../components/products/partials/subMenuView.vue'
export { default as SolutionsPagesAirline } from '../../components/solutions/pages/Airline.vue'
export { default as SolutionsPagesEPC } from '../../components/solutions/pages/EPC.vue'
export { default as SolutionsPagesEnergy } from '../../components/solutions/pages/Energy.vue'
export { default as SolutionsPagesMotor } from '../../components/solutions/pages/Motor.vue'
export { default as SolutionsPagesOil } from '../../components/solutions/pages/Oil.vue'
export { default as SolutionsPartialsBgNormalPart } from '../../components/solutions/partials/BgNormalPart.vue'
export { default as SolutionsPartialsInfographicPart } from '../../components/solutions/partials/InfographicPart.vue'
export { default as SolutionsPartialsIssuePart } from '../../components/solutions/partials/IssuePart.vue'
export { default as SolutionsPartialsOfferPart } from '../../components/solutions/partials/OfferPart.vue'
export { default as SolutionsPartialsRoiPart } from '../../components/solutions/partials/RoiPart.vue'
export { default as SolutionsPartialsSubMenu } from '../../components/solutions/partials/subMenu.vue'
export { default as SolutionsPartialsSubMenuAirLine } from '../../components/solutions/partials/subMenuAirLine.vue'
export { default as SolutionsPartialsSubMenuEpc } from '../../components/solutions/partials/subMenuEpc.vue'
export { default as SolutionsPartialsSubMenuMotor } from '../../components/solutions/partials/subMenuMotor.vue'
export { default as SolutionsPartialsSubMenuOil } from '../../components/solutions/partials/subMenuOil.vue'
export { default as SupportFaqAsideMenu } from '../../components/support/faq/AsideMenu.vue'
export { default as SupportFaqContents } from '../../components/support/faq/FaqContents.vue'
export { default as SupportFaqGoogleMap } from '../../components/support/faq/GoogleMap.vue'
export { default as SupportLearningCenterAsideMenu } from '../../components/support/learning-center/AsideMenu.vue'
export { default as SupportLearningCenterListTabMenu } from '../../components/support/learning-center/ListTabMenu.vue'
export { default as SupportLearningCenterStaticModule } from '../../components/support/learning-center/StaticModule.vue'
export { default as SupportLearningCenterUserManual } from '../../components/support/learning-center/userManual.vue'
export { default as SupportLearningCenterVideoRealGuide } from '../../components/support/learning-center/videoRealGuide.vue'
export { default as SupportLearningCenterVideoTutorial } from '../../components/support/learning-center/videoTutorial.vue'
export { default as SupportNoticeAsideMenu } from '../../components/support/notice/AsideMenu.vue'
export { default as SupportNoticeContents } from '../../components/support/notice/NoticeContents.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
